# Generated by Django 3.2.6 on 2021-09-01 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.IntegerField(max_length=200)),
                ('currency', models.IntegerField(max_length=200)),
                ('twenty', models.IntegerField(max_length=10)),
                ('forty', models.IntegerField(max_length=10)),
                ('fortyhc', models.IntegerField(max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containers.contract')),
            ],
        ),
    ]
